webapp/src/Entity/Team.php
<?php declare(strict_types=1);

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;
use OpenApi\Annotations as OA;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * All teams participating in the contest.
 *
 * @ORM\Entity()
 * @ORM\Table(
 *     name="team",
 *     options={"collation"="utf8mb4_unicode_ci", "charset"="utf8mb4"},
 *     indexes={
 *         @ORM\Index(name="affilid", columns={"affilid"}),
 *         @ORM\Index(name="categoryid", columns={"categoryid"})
 *     },
 *     uniqueConstraints={
 *         @ORM\UniqueConstraint(name="externalid", columns={"externalid"}, options={"lengths": {190}}),
 *     })
 * @UniqueEntity("externalid")
 */
class Team extends BaseApiEntity implements ExternalRelationshipEntityInterface, AssetEntityInterface
{
    const DONT_ADD_USER = 'dont-add-user';
    const CREATE_NEW_USER = 'create-new-user';
    const ADD_EXISTING_USER = 'add-existing-user';

    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer", name="teamid", length=4, options={"comment"="Team ID", "unsigned"=true}, nullable=false)
     * @Serializer\SerializedName("id")
     * @Serializer\Type("string")
     */
    protected ?int $teamid = null;

    /**
     * @ORM\Column(type="string", name="externalid", length=255,
     *     options={"comment"="Team ID in an external system",
     *              "collation"="utf8mb4_bin"},
     *     nullable=true)
     * @Serializer\Exclude()
     */
    protected ?string $externalid = null;

    /**
     * @ORM\Column(type="string", name="icpcid", length=255, options={"comment"="Team ID in the ICPC system",
     *                            "collation"="utf8mb4_bin"}, nullable=true)
     * @Serializer\SerializedName("icpc_id")
     * @OA\Property(nullable=true)
     */
    protected ?string $icpcid;

    /**
     * @ORM\Column(type="string", name="name", length=255, options={"comment"="Team name", "collation"="utf8mb4_bin"},
     *                            nullable=false)
     */
    private string $name = '';

    /**
     * @ORM\Column(type="string", name="display_name", length=255,
     *     options={"comment"="Team display name", "collation"="utf8mb4_bin"},
     *                            nullable=true)
     * @OA\Property(nullable=true)
     */
    private ?string $display_name = null;

    /**
     * @ORM\Column(type="boolean", name="enabled",
     *     options={"comment"="Whether the team is visible and operational",
     *              "default"=1},
     *     nullable=false)
     * @Serializer\Exclude()
     */
    private bool $enabled = true;

    /**
     * @ORM\Column(type="text", length=4294967295, name="publicdescription",
     *     options={"comment"="Public team definition; for example: Team member names (freeform)"},
     *                          nullable=true)
     * @Serializer\Groups({"Nonstrict"})
     * @OA\Property(nullable=true)
     */
    private ?string $publicDescription;

    /**
     * @ORM\Column(type="string", length=255, name="room", options={"comment"="Physical location of team"},
     *                            nullable=true)
     * @Serializer\Exclude()
     */
    private ?string $room;

    /**
     * @ORM\Column(type="text", length=4294967295, name="internalcomments",
     *     options={"comment"="Internal comments about this team (jury only)"},
     *                          nullable=true)
     * @Serializer\Exclude()
     */
    private ?string $internalComments;

    /**
     * @var double|string|null
     * @ORM\Column(type="decimal", precision=32, scale=9, name="judging_last_started",
     *     options={"comment"="Start time of last judging for prioritization",
     *              "unsigned"=true}, nullable=true)
     * @Serializer\Exclude()
     */
    private $judging_last_started;

    /**
     * @ORM\Column(type="integer", name="penalty",
     *     options={"comment"="Additional penalty time in minutes","default"=0},
     *     nullable=false)
     * @Serializer\Exclude()
     */
    private int $penalty = 0;

    /**
     * @Serializer\Exclude()
     */
    private string $addUserForTeam = self::DONT_ADD_USER;

    /**
     * @Assert\Regex("/^[a-z0-9@._-]+$/i", message="Only alphanumeric characters and _-@. are allowed")
     * @Serializer\Exclude
     */
    private ?string $newUsername = null;

    /**
     * @Serializer\Exclude
     */
    private ?User $existingUser;

    /**
     * @Assert\File(mimeTypes={"image/png","image/jpeg","image/svg+xml"}, mimeTypesMessage="Only PNG's, JPG's and SVG's are allowed")
     * @Serializer\Exclude()
     */
    private ?UploadedFile $photoFile = null;

    /**
     * @Serializer\Exclude()
     */
    private bool $clearPhoto = false;

    /**
     * @ORM\ManyToOne(targetEntity="TeamAffiliation", inversedBy="teams")
     * @ORM\JoinColumn(name="affilid", referencedColumnName="affilid", onDelete="SET NULL")
     * @Serializer\Exclude()
     */
    private ?TeamAffiliation $affiliation;

    /**
     * @ORM\ManyToOne(targetEntity="TeamCategory", inversedBy="teams")
     * @ORM\JoinColumn(name="categoryid", referencedColumnName="categoryid", onDelete="CASCADE")
     * @Serializer\Exclude()
     */
    private ?TeamCategory $category;

    /**
     * @ORM\ManyToMany(targetEntity="Contest", mappedBy="teams")
     * @Serializer\Exclude()
     */
    private Collection $contests;

    /**
     * @ORM\OneToMany(targetEntity="User", mappedBy="team", cascade={"persist"})
     * @Serializer\Exclude()
     * @Assert\Valid()
     */
    private Collection $users;

    /**
     * @ORM\OneToMany(targetEntity="Submission", mappedBy="team")
     * @Serializer\Exclude()
     */
    private Collection $submissions;

    /**
     * @ORM\OneToMany(targetEntity="Clarification", mappedBy="sender")
     * @Serializer\Exclude()
     */
    private Collection $sent_clarifications;

    /**
     * @ORM\OneToMany(targetEntity="Clarification", mappedBy="recipient")
     * @Serializer\Exclude()
     */
    private Collection $received_clarifications;

    /**
     * @ORM\ManyToMany(targetEntity="Clarification")
     * @ORM\JoinTable(name="team_unread",
     *                joinColumns={@ORM\JoinColumn(name="teamid", referencedColumnName="teamid", onDelete="CASCADE")},
     *                inverseJoinColumns={@ORM\JoinColumn(name="mesgid", referencedColumnName="clarid", onDelete="CASCADE")}
     * )
     * @Serializer\Exclude()
     */
    private Collection $unread_clarifications;

    public function setTeamid(int $teamid): Team
    {
        $this->teamid = $teamid;
        return $this;
    }

    public function getTeamid(): ?int
    {
        return $this->teamid;
    }

    public function setExternalid(?string $externalid): Team
    {
        $this->externalid = $externalid;
        return $this;
    }

    public function getExternalid(): ?string
    {
        return $this->externalid;
    }

    public function setIcpcid(?string $icpcid): Team
    {
        $this->icpcid = $icpcid;

        return $this;
    }

    public function getIcpcId(): ?string
    {
        return $this->icpcid;
    }

    public function setName(string $name): Team
    {
        $this->name = $name;
        return $this;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setDisplayName(?string $display_name): self
    {
        $this->display_name = $display_name;
        return $this;
    }

    public function getDisplayName(): ?string
    {
        return $this->display_name;
    }

    public function getEffectiveName(): string
    {
        return $this->getDisplayName() ?? $this->getName();
    }

    public function getShortDescription(): string
    {
        return $this->getEffectiveName();
    }

    public function setEnabled(bool $enabled): Team
    {
        $this->enabled = $enabled;
        return $this;
    }

    public function getEnabled(): bool
    {
        return $this->enabled;
    }

    public function setPublicDescription(?string $publicDescription): Team
    {
        $this->publicDescription = $publicDescription;
        return $this;
    }

    public function getPublicDescription(): ?string
    {
        return $this->publicDescription;
    }

    public function setRoom(?string $room): Team
    {
        $this->room = $room;
        return $this;
    }

    public function getRoom(): ?string
    {
        return $this->room;
    }

    public function setInternalComments(?string $comments): Team
    {
        $this->internalComments = $comments;
        return $this;
    }

    public function getInternalComments(): ?string
    {
        return $this->internalComments;
    }

    /** @param string|float $judgingLastStarted */
    public function setJudgingLastStarted($judgingLastStarted): Team
    {
        $this->judging_last_started = $judgingLastStarted;
        return $this;
    }

    /** @return string|float */
    public function getJudgingLastStarted()
    {
        return $this->judging_last_started;
    }

    public function setPenalty(int $penalty): Team
    {
        $this->penalty = $penalty;
        return $this;
    }

    /**
     * Set whether to add a new user for this team, link an existing one or do nothing.
     * Will not be stored, but is used in validation.
     */
    public function setAddUserForTeam(string $addUserForTeam): void
    {
        $this->addUserForTeam = $addUserForTeam;
    }

    /**
     * Set the username of a new user to add when $addUserForTeam is
     * static::CREATE_NEW_USER
     * Will not be stored, but is used in validation.
     */

webapp/src/Controller/Team/ClarificationController.php
<?php declare(strict_types=1);

namespace App\Controller\Team;

use App\Controller\BaseController;
use App\Entity\Clarification;
use App\Entity\Contest;
use App\Entity\Problem;
use App\Entity\Team;
use App\Form\Type\TeamClarificationType;
use App\Service\ConfigurationService;
use App\Service\DOMJudgeService;
use App\Service\EventLogService;
use App\Utils\Utils;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\Query\Expr\Join;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class ClarificationController
 *
 * @Route("/team")
 * @IsGranted("ROLE_TEAM")
 * @Security("user.getTeam() !== null", message="You do not have a team associated with your account. ")
 *
 * @package App\Controller\Team
 */
class ClarificationController extends BaseController
{
    protected DOMJudgeService $dj;
    protected ConfigurationService $config;
    protected EntityManagerInterface $em;
    protected EventLogService $eventLogService;
    protected FormFactoryInterface $formFactory;

    public function __construct(
        DOMJudgeService $dj,
        ConfigurationService $config,
        EntityManagerInterface $em,
        EventLogService $eventLogService,
        FormFactoryInterface $formFactory
    ) {
        $this->dj              = $dj;
        $this->config          = $config;
        $this->em              = $em;
        $this->eventLogService = $eventLogService;
        $this->formFactory     = $formFactory;
    }

    /**
     * @Route("/clarifications/{clarId<\d+>}", name="team_clarification")
     * @throws NonUniqueResultException
     */
    public function viewAction(Request $request, int $clarId): Response
    {
        $categories = $this->config->get('clar_categories');
        $user       = $this->dj->getUser();
        $team       = $user->getTeam();
        $contest    = $this->dj->getCurrentContest($team->getTeamid());
        /** @var Clarification|null $clarification */
        $clarification = $this->em->createQueryBuilder()
            ->from(Clarification::class, 'c')
            ->leftJoin('c.problem', 'p')
            ->leftJoin('c.contest', 'co')
            ->leftJoin('p.contest_problems', 'cp', Join::WITH, 'cp.contest = :contest')
            ->select('c, p, co')
            ->andWhere('c.contest = :contest')
            ->andWhere('c.clarid = :clarId')
            ->setParameter('contest', $contest)
            ->setParameter('clarId', $clarId)
            ->getQuery()
            ->getOneOrNullResult();

        $formData = [];
        if ($clarification) {
            if ($clarification->getProblem()) {
                $formData['subject'] = sprintf('%d-%d', $clarification->getContest()->getCid(), $clarification->getProblem()->getProbid());
            } else {
                $formData['subject'] = sprintf('%d-%s', $clarification->getContest()->getCid(), $clarification->getQueue());
            }

            $message = '';
            $text    = explode("\n", Utils::wrapUnquoted($clarification->getBody()), 75);
            foreach ($text as $line) {
                $message .= "> $line\n";
            }

            $formData['message'] = $message;
        }
        $form = $this->formFactory
            ->createBuilder(TeamClarificationType::class, $formData)
            ->setAction($this->generateUrl('team_clarification', ['clarId' => $clarId]))
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->newClarificationHelper($form, $contest, $team);
            return $this->redirectToRoute('team_index');
        }

        if ($clarification === null) {
            throw new NotFoundHttpException(sprintf('Clarification %d not found', $clarId));
        }

        if (!$team->canViewClarification($clarification)) {
            throw new HttpException(401, 'Permission denied');
        }

        // Get the "parent" message if we have one.
        if ($clarification->getInReplyTo()) {
            $clarification = $clarification->getInReplyTo();
        }

        // Mark clarification as read.
        $team->removeUnreadClarification($clarification);
        foreach ($clarification->getReplies() as $reply) {
            $team->removeUnreadClarification($reply);
        }
        $this->em->flush();

        $data = [
            'clarification' => $clarification,
            'team' => $team,
            'categories' => $categories,
            'form' => $form->createView(),
        ];

        if ($request->isXmlHttpRequest()) {
            return $this->render('team/clarification_modal.html.twig', $data);
        } else {
            return $this->render('team/clarification.html.twig', $data);
        }
    }

    /**
     * @Route("/clarifications/add", name="team_clarification_add")
     */
    public function addAction(Request $request): Response
    {
        $categories = $this->config->get('clar_categories');
        $user       = $this->dj->getUser();
        $team       = $user->getTeam();
        $contest    = $this->dj->getCurrentContest($team->getTeamid());

        $formData = [];
        $form     = $this->formFactory
            ->createBuilder(TeamClarificationType::class, $formData)
            ->setAction($this->generateUrl('team_clarification_add'))
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->newClarificationHelper($form, $contest, $team);
            return $this->redirectToRoute('team_index');
        }

        $data = [
            'categories' => $categories,
            'form' => $form->createView(),
        ];

        if ($request->isXmlHttpRequest()) {
            return $this->render('team/clarification_add_modal.html.twig', $data);
        } else {
            return $this->render('team/clarification_add.html.twig', $data);
        }
    }

    /**
     * @throws NonUniqueResultException
     */
    private function newClarificationHelper(
        FormInterface $form,
        ?Contest $contest,
        Team $team
    ): void {
        $formData = $form->getData();
        // First part will always be the contest ID, as Symfony will validate this.
        [, $problemId] = explode('-', $formData['subject']);
        $problem = null;
        $category = null;
        $queue = null;
        if (!ctype_digit($problemId)) {
            $category = $problemId;
        } else {
            $problem = $this->em->getRepository(Problem::class)->find($problemId);
            $queue = $this->config->get('clar_default_problem_queue');
            if ($queue === "") {
                $queue = null;
            }
        }

        $newClarification = new Clarification();
        $newClarification
            ->setContest($contest)
            ->setSubmittime(Utils::now())
            ->setSender($team)
            ->setProblem($problem)
            ->setCategory($category)
            ->setQueue($queue)
            ->setBody($formData['message']);

        $this->em->persist($newClarification);
        $this->em->flush();

        $this->dj->auditlog('clarification', $newClarification->getClarid(), 'added', null, null,
            $contest->getCid());
        $this->eventLogService->log('clarification', $newClarification->getClarid(), 'create', $contest->getCid());

        $this->addFlash('success', 'Clarification sent to the jury');
    }
}

webapp/templates/team/partials/clarification.html.twig
<div class="card mb-3">
    <div class="card-header">
        <div class="row">
            <div class="col-sm">
                Subject:
                {% if clarification.problem %}
                    Problem {{ clarification.problem.contestProblems.first.shortname }}: {{ clarification.problem.name }}
                {% elseif clarification.category %}
                    {{ categories[clarification.category]|default('general') }}
                {% else %}
                    General issue
                {% endif %}
            </div>
            <div class="col-sm text-muted text-right">{{ clarification.submittime | printtimeHover(clarification.contest) }}</div>
        </div>
    </div>
    <div class="card-body">
        <div class="card-title">
            <div class="row">
                <div class="col-sm">
                    From:
                    {% if clarification.sender is not empty %}
                        {{ clarification.sender.effectiveName }} (t{{ clarification.sender.teamid }})
                    {% else %}
                        Jury
                    {% endif %}
                </div>
                <div class="col-sm">To:
                    {% if clarification.recipient is not empty %}
                        {{ clarification.recipient.effectiveName }} (t{{ clarification.recipient.teamid }})
                    {% elseif clarification.sender is not null %}
                        Jury
                    {% else %}
                        <strong>All</strong>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="card-text">
            <pre class="output-text bg-light p-3">{{ clarification.body|wrapUnquoted(78) }}</pre>
        </div>
    </div>
</div>

webapp/templates/team/partials/clarification_content.html.twig
<div class="container clarificationform">
    {% include 'team/partials/clarification.html.twig' with {clarification: clarification } %}
    {% for reply in clarification.replies | filter(reply => team.canViewClarification(reply)) %}
        {% include 'team/partials/clarification.html.twig' with {clarification: reply } %}
    {% endfor %}
</div>

<div class="collapse mt-3 container clarificationform" id="collapsereplyform">
    <div class="card card-body">
        {{ form_start(form) }}
        {{ form_row(form.recipient) }}
        {{ form_row(form.subject) }}
        {{ form_row(form.message) }}
        <div class="form-group">
            <button type="submit" name="submit" class="btn btn-primary">
                <i class="fas fa-envelope"></i> Send
            </button>
        </div>
        {{ form_end(form) }}
    </div>
</div>

webapp/templates/team/partials/clarification_list.html.twig
<div class="table-wrapper">
    <table class="data-table table table-striped table-hover table-sm" style="width:100%;">
        <thead class="thead-light">
        <tr>
            <th scope="col">time</th>
            <th scope="col">from</th>
            <th scope="col">to</th>
            <th scope="col">subject</th>
            <th scope="col">text</th>
        </tr>
        </thead>
        <tbody>
        {%- for clarification in clarifications %}
            {%- set link = path('team_clarification', {clarId: clarification.clarid}) %}

            <tr class="{% if team.unreadClarifications.contains(clarification) %}unseen{% endif %}">
                <td>
                    <a data-ajax-modal data-ajax-modal-after="markSeen" href="{{ link }}">
                        {{ clarification.submittime | printtime(null, clarification.contest) }}
                    </a>
                </td>
                {%- if clarification.sender is null %}
                    {%- set sender = 'Jury' %}
                    {%- if clarification.recipient is null %}
                        {%- set recipient = 'All' %}
                    {%- else %}
                        {%- set recipient = clarification.recipient.effectiveName %}
                    {%- endif %}
                {%- else %}
                    {%- set recipient = 'Jury' %}
                    {%- set sender = clarification.sender.effectiveName %}
                {%- endif %}

                <td>
                    <a data-ajax-modal data-ajax-modal-after="markSeen" href="{{ link }}" title="{{ sender }}">
                        {{ sender | u.truncate(teamname_max_length, '…') }}
                    </a>
                </td>
                <td>
                    <a data-ajax-modal data-ajax-modal-after="markSeen" href="{{ link }}" title="{{ recipient }}">
                        {{ recipient | u.truncate(teamname_max_length, '…') }}
                    </a>
                </td>
                <td>
                    <a data-ajax-modal data-ajax-modal-after="markSeen" href="{{ link }}">
                        {%- if clarification.problem -%}
                            problem {{ clarification.problem.contestProblems.first | problemBadge -}}
                        {%- elseif clarification.category -%}
                            {{- categories[clarification.category]|default('general') -}}
                        {%- else -%}
                            general
                        {%- endif -%}
                    </a>
                </td>

                <td>
                    <a data-ajax-modal data-ajax-modal-after="markSeen" href="{{ link }}">
                        {{ clarification.summary }}
                    </a>
                </td>
            </tr>
        {%- endfor %}

        </tbody>
    </table>
</div>

webapp/templates/team/partials/index_content.html.twig
{% if contest is empty %}
    <h1 id="teamwelcome" class="text-center">Welcome team <span id="teamwelcometeam">{{ team.effectiveName }}</span>!</h1>
    <h2 id="contestnotstarted" class="text-center">There's no active contest for you (yet).</h2>
{% elseif not contest.freezeData.started %}
    <h1 id="teamwelcome" class="text-center">Welcome team <span id="teamwelcometeam">{{ team.effectiveName }}</span>!</h1>
    <h2 id="contestnotstarted" class="text-center">
        Contest {{ contest | printContestStart }}
    </h2>
{% else %}

    <div id="teamscoresummary">
        {% set displayRank = not contest.freezeData.showFrozen %}
        {% include 'partials/scoreboard_table.html.twig' with {displayRank: displayRank, jury: false, public: false} %}
    </div>

    <div class="mt-4" data-flash-messages>
        {% include 'partials/messages.html.twig' %}
        {% if not contest.allowSubmit %}
            {% include 'partials/alert.html.twig' with {'type': 'danger', 'message': 'Submissions (temporarily) disabled.'} %}
        {% endif %}
    </div>

    <div class="row">
        <div class="col">
            <h1 class="teamoverview">Submissions</h1>

            {% include 'team/partials/submission_list.html.twig' %}
        </div>
        <div class="col">
            <h1 class="teamoverview">Clarifications</h1>
            {% if clarifications is empty %}
                <p class="nodata">No clarifications.</p>
            {% else %}
                {% include 'team/partials/clarification_list.html.twig' with {clarifications: clarifications} %}
            {% endif %}

            <h1 class="teamoverview">Clarification Requests</h1>
            {% if clarificationRequests is empty %}
                <p class="nodata">No clarification request.</p>
            {% else %}
                {% include 'team/partials/clarification_list.html.twig' with {clarifications: clarificationRequests} %}
            {% endif %}

            <div class="m-1">
                <a href="{{ path('team_clarification_add') }}" class="btn btn-secondary btn-sm" data-ajax-modal>
                    request clarification
                </a>
            </div>
        </div>
    </div>
{% endif %}

{% if ajax is defined and ajax %}
    {% include 'partials/scoreboard_progress_bar.html.twig' with {margin: -9, contest: current_team_contest} %}
{% endif %}

webapp/templates/team/partials/submission_list.html.twig
{# Render a list of submissions for a team page #}
{# @var submission \App\Entity\Submission #}

{% if submissions is empty %}
    <div class="alert alert-warning">No submissions</div>
{% else %}
    <table class="data-table table table-hover table-striped table-sm submissions-table">
        <thead class="thead-light">
        <tr>
            <th scope="col">time</th>
            <th scope="col">problem</th>
            <th scope="col">lang</th>
            <th scope="col">result</th>
            <th scope="col">testcase</th>
            {% if allowDownload %}
                <th scope="col"></th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {%- for submission in submissions %}
            {% set link = null %}
            {% if submission.submittime < current_team_contest.endtime and submission.result and submission.judgings.first is not empty and submission.judgings.first.result is not empty and (not verificationRequired or submission.judgings.first.verified) %}
                {% set link = path('team_submission', {submitId: submission.submitid}) %}
            {% endif %}

            {% set classes = '' %}
            {% if not submission.valid %}
                {% set classes = classes ~ ' ignore' %}
            {% endif %}
            {% if submission.judgings.first is empty or not submission.judgings.first.seen %}
                {% set classes = classes ~ ' unseen' %}
            {% endif %}
            <tr class="{{ classes }}">
                <td>
                    <a data-ajax-modal data-ajax-modal-after="markSeen" {% if link %}href="{{ link }}"{% endif %}>
                        {{ submission.submittime | printtime(null, submission.contest) }}
                    </a>
                </td>
                <td class="probid">
                    <a data-ajax-modal data-ajax-modal-after="markSeen" {% if link %}href="{{ link }}"{% endif %} title="{{ submission.problem.name }}">
                        {{ submission.contestProblem | problemBadge }}
                    </a>
                </td>
                <td class="langid">
                    <a data-ajax-modal data-ajax-modal-after="markSeen" {% if link %}href="{{ link }}"{% endif %} title="{{ submission.language.name }}">
                        {{ submission.language.langid }}
                    </a>
                </td>
                <td>
                    <a data-ajax-modal data-ajax-modal-after="markSeen" {% if link %}href="{{ link }}"{% endif %}>
                        {%- if submission.submittime > submission.contest.endtime %}
                            {{ 'too-late' | printResult }}
                        {%- elseif submission.judgings.first is empty or submission.judgings.first.result is empty %}
                            {{- '' | printResult -}}
                        {%- elseif verificationRequired and not submission.judgings.first.verified %}
                            {{- '' | printResult -}}
                        {%- else %}
                            {{- submission.judgings.first.result | printResult -}}
                        {%- endif %}
                    </a>
                </td>
                <td>
                    {% set judging = submission.judgings.first %}
                    {% if judging and judging.runs is not empty %}
                        {% set total = judging.runs|length %}
                        {% set correct = 0 %}
                        {% for run in judging.runs %}
                            {% if run.runresult == 'correct' %}
                                {% set correct = correct + 1 %}
                            {% endif %}
                        {% endfor %}
                        <span class="ms-1 badge bg-primary">{{ correct }}/{{ total }}</span>
                    {% else %}
                        …
                    {% endif %}
                </td>
        {% if allowDownload %}
                <td>
                    <a title="Download submission ZIP" aria-label="download submission zip" class="btn btn-light" href="{{ path('team_submission_download', {'submitId': submission.submitid}) }}">
                        <i class="fa fa-file-archive"></i>
                    </a>
                </td>
        {% endif %}
            </tr>
        {%- endfor %}
        </tbody>
    </table>
{% endif %}